<a href="https://colab.research.google.com/github/kristynpantoja/bsg_pytorch/blob/master/BSGcollab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn import Parameter
import torch.nn.functional as F
import math


from sklearn.datasets import fetch_20newsgroups
import numpy as np
import torch
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

import argparse
from types import SimpleNamespace

# import gensim.downloader as api
# from gensim.models import Word2Vec, FastText, KeyedVectors
# from os.path import isfile

import random
random.seed(1234)

import pandas as pd
import matplotlib.pyplot as plt

import re, string, unicodedata
import nltk
from nltk import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer, WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer

In [25]:
# arguments 



window = 2




In [4]:
nltk.download("stopwords")
nltk.download("punkt")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kristyn/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/kristyn/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
# # preprocessing stuff

# def remove_non_ascii(words):
#     """Remove non-ASCII characters from list of tokenized words"""
#     new_words = []
#     for word in words:
#         new_word = unicodedata.normalize('NFKD', word).encode('ascii', 'ignore').decode('utf-8', 'ignore')
#         new_words.append(new_word)
#     return new_words

# def to_lowercase(words):
#     """Convert all characters to lowercase from list of tokenized words"""
#     new_words = []
#     for word in words:
#         new_word = word.lower()
#         new_words.append(new_word)
#     return new_words

# def remove_punctuation(words):
#     """Remove punctuation from list of tokenized words"""
#     new_words = []
#     for word in words:
#         new_word = re.sub(r'[^\w\s]', '', word)
#         if new_word != '':
#             new_words.append(new_word)
#     return new_words

# def remove_stopwords(words):
#     """Remove stop words from list of tokenized words"""
#     new_words = []
#     for word in words:
#         if word not in stopwords.words('english'):
#             new_words.append(word)
#     return new_words

# def stem_words(words):
#     """Stem words in list of tokenized words"""
#     stemmer = LancasterStemmer()
#     stems = []
#     for word in words:
#         stem = stemmer.stem(word)
#         stems.append(stem)
#     return stems

# def lemmatize_verbs(words):
#     """Lemmatize verbs in list of tokenized words"""
#     lemmatizer = WordNetLemmatizer()
#     lemmas = []
#     for word in words:
#         lemma = lemmatizer.lemmatize(word, pos='v')
#         lemmas.append(lemma)
#     return lemmas

# def normalize(words): # preprocessing step
#     words = remove_non_ascii(words)
#     words = to_lowercase(words)
#     words = remove_punctuation(words)
# #     words = remove_stopwords(words)
#     return words

# would be faster to preprocess before tokenizing, I think

In [13]:
# Get corpus: 20 news groups

newsgroups_train = fetch_20newsgroups(subset='train')

# tokenize and preprocess

tokenizer = RegexpTokenizer(u'(?ui)\\b[a-z]{3,}\\b')

tokenized_corpus = [tokenizer.tokenize(document.lower()) for document in newsgroups_train.data]

# normalize_corpus = [normalize(document) for document in tokenized_corpus]

In [14]:
# get vocabulary

flattened = [word for document in tokenized_corpus for word in document]
vocabulary = set(flattened)
vocabulary = list(vocabulary)
len(vocabulary)

81072

In [ ]:
# # get vocabulary: with some preprocessing
# vectorizer = CountVectorizer(stop_words = 'english', 
#                              min_df=.01, max_df=0.9, 
#                              token_pattern = u'(?ui)\\b[a-z]{3,}\\b')

# count_vecs = vectorizer.fit_transform(newsgroups_train.data)

# # doc_term_matrix = count_vecs.toarray()
# # doc_term_matrix.shape # number of documents, number of words (in vocab)

# # note: vectorizer.get_feature_names() != vectorizer.vocabulary_

# vocabulary = vectorizer.get_feature_names()

In [19]:
# # vocabulary = []
# # for sentence in tokenized_corpus:
# #     for token in sentence:
# #         if token not in vocabulary:
# #             vocabulary.append(token)

word2idx = {w: idx + 1 for (idx , w) in enumerate(vocabulary)}
idx2word = {idx + 1: w for (idx, w) in enumerate(vocabulary)}

vocabulary_size = len(vocabulary)

# idx_pairs = []
# # for each sentence
# for sentence in tokenized_corpus:
#     indices = [word2idx[word] for word in sentence]
#     # for each word, threated as center word
#     for center_word_pos in range(len(indices)):
#         # for each window position
#         for w in range(-window_size, window_size + 1):
#             context_word_pos = center_word_pos + w
#             # make soure not jump out sentence
#             if context_word_pos < 0 or context_word_pos >= len(indices) or center_word_pos == context_word_pos:
#                 continue
#             context_word_idx = indices[context_word_pos]
#             idx_pairs.append((indices[center_word_pos], context_word_idx))

# idx_pairs = np.array(idx_pairs) # it will be useful to have this as numpy array

In [22]:
indexed_corpus = []
# for each document
for document in tokenized_corpus:
    ragged_array = []
    # for each word
    for word in document:
        ragged_array.append(word2idx[word])
    indexed_corpus.append(ragged_array)

In [24]:
print(tokenized_corpus[0])
print(len(tokenized_corpus[0]))
print(indexed_corpus[0])
print(len(indexed_corpus[0]))

['from', 'lerxst', 'wam', 'umd', 'edu', 'where', 'thing', 'subject', 'what', 'car', 'this', 'nntp', 'posting', 'host', 'wam', 'umd', 'edu', 'organization', 'university', 'maryland', 'college', 'park', 'lines', 'was', 'wondering', 'anyone', 'out', 'there', 'could', 'enlighten', 'this', 'car', 'saw', 'the', 'other', 'day', 'was', 'door', 'sports', 'car', 'looked', 'from', 'the', 'late', 'early', 'was', 'called', 'bricklin', 'the', 'doors', 'were', 'really', 'small', 'addition', 'the', 'front', 'bumper', 'was', 'separate', 'from', 'the', 'rest', 'the', 'body', 'this', 'all', 'know', 'anyone', 'can', 'tellme', 'model', 'name', 'engine', 'specs', 'years', 'production', 'where', 'this', 'car', 'made', 'history', 'whatever', 'info', 'you', 'have', 'this', 'funky', 'looking', 'car', 'please', 'mail', 'thanks', 'brought', 'you', 'your', 'neighborhood', 'lerxst']
97
[78448, 76643, 8341, 61107, 11216, 44509, 6544, 59970, 71648, 41898, 46184, 52833, 33033, 70083, 8341, 61107, 11216, 67517, 32560, 

In [26]:
padded_corpus = [np.pad(document, (window,window), 'constant', constant_values=(0, 0)) 
                 for document in indexed_corpus]



In [35]:
test

test = padded_corpus[0]
contexts = []
for context in range(window, len(test) - window):
    center_word = test[context]
    context_words = np.concatenate((test[(context - window) : context], 
                                    test[context + 1 : context + window + 1]))
    contexts.append((center_word, context_words))
print(len(contexts))
print(len(indexed_corpus[0]))
contexts

array([    0,     0, 78448, 76643,  8341, 61107, 11216, 44509,  6544,
       59970, 71648, 41898, 46184, 52833, 33033, 70083,  8341, 61107,
       11216, 67517, 32560, 52327, 35572, 28150, 35811, 54779, 55247,
       55823, 53054, 45688, 14352, 72340, 46184, 41898, 52948, 13468,
       22816, 10371, 54779, 13931, 79462, 41898, 20817, 78448, 13468,
       14074, 10331, 54779, 24786, 10833, 13468, 12834, 26739, 66602,
       48261, 30054, 13468,  6310, 13749, 54779, 26931, 78448, 13468,
       35761, 13468, 42671, 46184, 64612, 56601, 55823, 25734, 46800,
        7313, 46382, 80707,  1513, 18684, 62633, 44509, 46184, 41898,
       45769, 80559, 79237, 45502, 19634, 45180, 46184, 48473, 26767,
       41898, 39163, 68034, 65412, 70832, 19634, 40506, 58495, 76643,
           0,     0])

In [38]:
test = padded_corpus[0]
contexts = []
for context in range(window, len(test) - window):
    center_word = test[context]
    context_words = np.concatenate((test[(context - window) : context], 
                                    test[context + 1 : context + window + 1]))
    contexts.append((center_word, context_words))
print(len(contexts))
print(len(indexed_corpus[0]))
contexts

97
97


[(78448, array([    0,     0, 76643,  8341])),
 (76643, array([    0, 78448,  8341, 61107])),
 (8341, array([78448, 76643, 61107, 11216])),
 (61107, array([76643,  8341, 11216, 44509])),
 (11216, array([ 8341, 61107, 44509,  6544])),
 (44509, array([61107, 11216,  6544, 59970])),
 (6544, array([11216, 44509, 59970, 71648])),
 (59970, array([44509,  6544, 71648, 41898])),
 (71648, array([ 6544, 59970, 41898, 46184])),
 (41898, array([59970, 71648, 46184, 52833])),
 (46184, array([71648, 41898, 52833, 33033])),
 (52833, array([41898, 46184, 33033, 70083])),
 (33033, array([46184, 52833, 70083,  8341])),
 (70083, array([52833, 33033,  8341, 61107])),
 (8341, array([33033, 70083, 61107, 11216])),
 (61107, array([70083,  8341, 11216, 67517])),
 (11216, array([ 8341, 61107, 67517, 32560])),
 (67517, array([61107, 11216, 32560, 52327])),
 (32560, array([11216, 67517, 52327, 35572])),
 (52327, array([67517, 32560, 35572, 28150])),
 (35572, array([32560, 52327, 28150, 35811])),
 (28150, array([

In [41]:
def document_contexts(document, window):
    contexts = []
    for context in range(window, len(document) - window):
        center_word = document[context]
        context_words = np.concatenate((document[(context - window) : context], 
                                        document[(context + 1) : (context + window + 1)]))
        contexts.append((center_word, context_words))
    return contexts

corpus_document_contexts = [document_contexts(document, window) for document in padded_corpus]



In [46]:
# we just care about contexts right now, so flatten the list
corpus_contexts = [pair for document_contexts in corpus_document_contexts for pair in document_contexts]



In [59]:
corpus_contexts[0:3]

[(78448, array([    0,     0, 76643,  8341])),
 (76643, array([    0, 78448,  8341, 61107])),
 (8341, array([78448, 76643, 61107, 11216]))]

In [88]:
corpus_contexts_tensor = list(map(list, zip(*corpus_contexts)))

corpus_center_words = torch.tensor(corpus_contexts_tensor[0], dtype = torch.int64)
corpus_context_words = torch.tensor(corpus_contexts_tensor[1], dtype = torch.int64)

In [77]:
corpus_center_words[0]

2539447

In [122]:
class BSG(nn.Module):
    def __init__(self, vocab_size, input_dim=50, hidden_dim=50, latent_dim=100, margin=1., model_name='BSG with the hinge loss'):
        super().__init__()
        """
        :param vocab_size: the number of unique words
        :param input_dim: the number of components in the encoder's word embeddings
        :param hidden_dim: the number of components in the encoder's hidden layer
        :param latent_dim: the number of components in the latent vector(also output word mu's)
        :param margin: margin constant present in the hinge loss
        """
        self.model_name = model_name
        self.vocab_size = vocab_size
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.latent_dim = latent_dim
        self.margin = margin

        # assign full parameters
#         self.params_full = self.__build_model()

        # extract only the actual parameter data-structures(tensors) as those will be optimized
#         self.params = [param.value for param in self.params_full.values()]

        # user accessible functions build ( e.g. training functions)
#         self.__build_functions()

        # encoder layers
        self.encoder_embedding = nn.Embedding(self.vocab_size, self.input_dim, padding_idx = 0) # R
        self.encoder_lin1 = nn.Linear(self.input_dim*2, self.hidden_dim) # M
        self.encoder_mu = nn.Linear(self.hidden_dim, self.latent_dim) # U -> mu
        self.encoder_logsigma = nn.Linear(self.hidden_dim, 1) # W -> log sigma
        
        # beta
        self.type_means = nn.Embedding(self.vocab_size, self.latent_dim)
        self.type_vars = nn.Embedding(self.vocab_size, 1)
        
        
    def encoder(self, centers_batch, contexts_batch):
#             batch_size = centers_batch.shape[0]
        sums = []
        for center, context in zip(centers_batch, contexts_batch):
            embed_center = self.encoder_embedding(center)
            embed_context = self.encoder_embedding(context)
            assert embed_context.shape[1] == self.input_dim, "context embedding is not a 2d tensor"
            center_repeats = embed_center.repeat(2*window, 1)
            concat = torch.cat((embed_context, center_repeats),1)
            sum_relu_en1 = F.relu(self.encoder_lin1(concat)).sum(0) # a vector
            sums.append(sum_relu_en1) # the vectors of sums
        sums = torch.stack(sums)
        mu = self.encoder_mu(sums)
        logsigma = self.encoder_logsigma(sums)
        return mu, logsigma
    
    def reparameterize(self, centers_batch, posterior_mean, posterior_logvar):
        eps = Variable(centers_batch.data.new().resize_as_(posterior_mean.data).normal_())
        z = posterior_mean + posterior_logvar.exp().sqrt() * eps
        return z
    
    def forward(...):
        # we don't need "generative"
        
    def loss(...):
    

In [120]:
model = BSG(vocabulary_size)

In [121]:
model.encoder(corpus_center_words[0:2], corpus_context_words[0:2])

tensor([    0,     0, 76643,  8341])
tensor([    0, 78448,  8341, 61107])


(tensor([[ 0.4168,  0.0151,  0.0527,  0.1214,  0.2159,  0.3550,  0.9378, -0.4628,
           0.3208, -0.9953,  0.8756, -0.0158,  0.7749, -0.8627, -0.0899, -0.1131,
          -0.0692,  0.5444, -0.5831,  0.2353,  0.9599, -0.5957, -0.0175,  0.6622,
           0.0822, -0.8282, -0.1901,  0.1267,  1.0530, -0.3138, -0.3428, -0.6973,
          -0.1746,  0.1953,  0.8736, -0.0369,  0.2305, -0.2232, -0.5545,  0.0326,
           0.3026, -0.3336, -0.0501,  0.2016,  0.7545, -0.6623,  0.9983, -0.6342,
           0.6753,  0.5179,  0.3885, -0.1390, -0.0223,  0.2696, -0.2688,  0.3179,
           0.7157,  0.2432, -0.2337, -0.6568, -0.4430,  0.0980, -0.3330,  0.1981,
          -0.1504, -0.3231, -0.0219, -0.0774, -0.0477,  0.3653,  0.0942,  1.1136,
           0.3845, -0.2861,  0.4235,  0.7650,  0.5147,  0.4593,  0.2526,  0.3219,
           0.5714, -0.9353, -0.2499, -0.1712, -0.4432, -0.1919, -0.4525, -0.0849,
          -0.0420,  0.4507, -0.0046,  0.3819,  0.4897,  0.6062,  0.0190, -0.0479,
           0.456